### ISSUE TITLE
Remove space at the start of response

### ISSUE THREAD

**Issue by GeekyGhost** [if-ai/ComfyUI-IF_AI_tools#43]
You wouldn't know how to remove the space from in front of response that gets added by default would you? I'm trying to pass true and false to a boolean to use as an automated type of switch, but I need to remove the space from in front of the response output. It works without the space, but with the output automatically adding it, it messes it up lol. 

<img width="871" alt="Screenshot 2024-05-26 100040" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/111990299/3a8981c8-ccd8-4a5f-af3d-f32b787e9fa0">

**Comment by GeekyGhost** [comment]
This is all that's holding me up lol. 

<img width="692" alt="Screenshot 2024-05-26 120124" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/111990299/a81e2cff-cc05-4849-ad86-e05cd9875e55">

**Comment by if-ai** [comment]
I apologize that I haven't got back to you to fix this easy issue. I was working on a new version of the node and making sure this was fix in various places but I couldn't push it due to an unforseen issue on how comfy works. 
Just to double check is possible the model itself has a empty space on the model file template in ollama this is an error they made when creating the template file and almost everyone copied it so it could be that too. Other than that I will inspect the current node to find where the problem is I am already applying some regex and strip to the responses so is weird it still comes like this

**Comment by GeekyGhost** [comment]
> I apologize that I haven't got back to you to fix this easy issue. I was working on a new version of the node and making sure this was fix in various places but I couldn't push it due to an unforseen issue on how comfy works. Just to double check is possible the model itself has a empty space on the model file template in ollama this is an error they made when creating the template file and almost everyone copied it so it could be that too. Other than that I will inspect the current node to find where the problem is I am already applying some regex and strip to the responses so is weird it still comes like this

No worries, completely understand. I got a bit caught up in my spritesheet maker which is way less intensive lol. I may have to add a node to format the text worst case scenario because it may just baked into the model like you said.
