### ISSUE TITLE
feature request  “Omost”

### ISSUE THREAD

**Issue by ghostrunner-art** [if-ai/ComfyUI-IF_AI_tools#50]
The recently released "Omost" seems to have some similarities to the functionality of your node.
Are you interested in supporting this?

https://github.com/lllyasviel/Omost

I found a plugin for "Omost" but it runs very slowly. 

https://github.com/huchenlei/ComfyUI_omost

If it is available in your plug-in, use Ollama to load the "Omost" model and integrate it into your node. There should be faster response times.

I hope you will support it. Because it works really well.

**Comment by if-ai** [comment]
Yes this is a great Idea I am going to work on this next week this and stylus to pull the loras

**Comment by ghostrunner-art** [comment]
hi, dear friend,
Do you remember this feature request?

**Comment by if-ai** [comment]
Yes, I do I had some issues with my computer that dragged the whole week but I just solved it. I will work on adding this. Thanks again for the request.

**Comment by ghostrunner-art** [comment]
I really like your plugin, it adds more possibilities to this world.

**Comment by if-ai** [comment]
Thanks also I will reopen the thread I realized I closed it by mistake

**Comment by if-ai** [comment]
I added Omost now is a tool 
![thorium_3tETdF9Wuy](https://github.com/user-attachments/assets/076a86c2-e583-4993-85d2-8633f92d1a35)

**Comment by ghostrunner-art** [comment]
It's really great, I'm going to try it right away.

**Comment by ghostrunner-art** [comment]
Sorry, I encountered an error. Below is a screenshot of the console.   

![image](https://github.com/user-attachments/assets/8b63486f-24c3-4b93-8dd2-dfea4eaf8dd0)
![image](https://github.com/user-attachments/assets/097f195a-0fcc-4eb5-8da8-cf2ede58781a)
![image](https://github.com/user-attachments/assets/7c453e68-b36e-4644-8d77-66afa8b6303a)

The above error occurs after all nodes of comfyui are loaded.
It should be these errors that cause the node in the "omost" sample workflow to report errors.
![image](https://github.com/user-attachments/assets/f13634e3-3073-4412-9b54-b92da6e6cc8d)

**Comment by if-ai** [comment]
You must move the IF_AI folder from the custom node folder to the input folder in ComfyUI/input/IF_AI

**Comment by ghostrunner-art** [comment]
What an astonishing job！    

I found a problem in the previous version.
The "control after generate" option in the "IF Chat Prompt👨‍💻" node seems to be unable to lock the "seed" value.
Because I set "control after generate" to "fixed". When running "Queue Prompt" for the second time, the "IF Chat Prompt👨‍💻" node still needs to be loaded. Is this a normal expectation?
![image](https://github.com/user-attachments/assets/fcc28035-ef6e-49f2-8b12-87b2266349cd)


Because "omost" runs very slowly, do not load the "IF Chat Prompt👨‍💻" node after locking "seed". This will allow you to obtain images that meet your requirements more quickly.

Only run it if the settings of the "IF Chat Prompt👨‍💻" node have changed.

It's all like "KSampler" locking "seed".


These contents are from Google Translate. If you don't understand, please tell me. If the wording is offensive, please forgive me.

**Comment by if-ai** [comment]
If you mean having Ollama not to generate the same tokens again? it always do the compute unfortunately I can't fix it. But there is a workaround.  Try selecting random instead of temperature because the seed is only one of them is supposed to be affecting the randomness 

![2mopHEjrYR](https://github.com/user-attachments/assets/60891e38-bbe6-4755-99c7-551a37a09798)


![jxke6qgHT8](https://github.com/user-attachments/assets/e6362fe1-aeae-4ce6-b8bb-4b71e6331293)

you can see if I use seed instead of temperature to control the randomness the second produces the same tokens and therefore the same images you also need fix seed in your ksamplers etc..

![explorer_PUFY9LHTRg](https://github.com/user-attachments/assets/564bbe79-b906-4fe9-a46e-4989fcb9260e)

Now if you want to use the same exact prompt you can put the IF Chat Node in a group and mute it

![cQh6kRkJIw](https://github.com/user-attachments/assets/da0dfe80-11bf-4339-9ba4-77890fa7d490)

**Comment by ghostrunner-art** [comment]
Well, this is also a good idea. I'm about to try it.
I would like to express my respect again, it is you who make the world of "AI" more colorful.

**Comment by if-ai** [comment]
Thank you. I am glad you find my node useful.
