### ISSUE TITLE
how to re-generate prompt with the same input text

### ISSUE THREAD

**Issue by nigo81** [if-ai/ComfyUI-IF_AI_tools#6]
<img width="1061" alt="image" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/38601513/f7fcf6c6-ce6d-43ee-849f-2c7bb4c62e9a">
After generating once, I want the model to regenerate the prompt without altering the input. However, currently, if the input text remains unchanged, it won't generate a new prompt but instead refers to a previously generated one.

I wonder if there's any way to achieve that every time I click on "generate," it regenerates a new Prompt?
Thanks!

**Comment by if-ai** [comment]
Yes, thank you I just notice that, I think it did work like that before but I must have changed something, I will add some features to get different prompts each time I think I had seed before but because seeds overrides temperature for ollama I had to trade it off, I will see how can I add that back

**Comment by if-ai** [comment]
The new random seed button will force a fixed seed if on and radom if off by default
