### ISSUE TITLE
Image To Prompt issue

### ISSUE THREAD

**Issue by MMoneer** [if-ai/ComfyUI-IF_AI_tools#9]
Hi, The Image to Prompt doesn't work correctly for generating images from the output prompt, it loops without outputting anything 
I use your workflow, Ollama version 1.30, Win 10, ComfyUI: 2092[96b4c7](2024-03-30) Manager: V2.11
You mention in the note "Ollama has a bug on the latest version" I don't know if you mean a bug to output the prompt (working fine) or generating images from the prompt

<img width="1921" alt="brave_01042024_049" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/18519387/104de8e8-224b-415e-a2d2-681d6927130d">
<img width="1339" alt="cmd_01042024_048" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/18519387/a24c536d-a399-4625-83be-71892f953cb1">
Also, what are the API key errors in the console 
Thank you

**Comment by if-ai** [comment]
Sorry it might be display text node has a bug, if Ollama is working now you can connect the response directly to the conditioning node you can still display the text just don't use the output of the display node for now I will fix that next update

**Comment by MMoneer** [comment]
> Sorry it might be display text node has a bug, if Ollama is working now you can connect the response directly to the conditioning node you can still display the text just don't use the output of the display node for now I will fix that next update

Thank You so much, it's working now

<img width="1921" alt="brave_02042024_050" src="https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/18519387/e575dadc-c88c-47e5-beab-a39268b416d6">

**Comment by alexdoroga** [comment]
I'm looking for a way to describe the image... all three models describe either a cyberdemon or a woman, regardless of the input image, llava 7b sometimes guesses what is in the picture, but almost always describes the style and scene with “Epic, ... Cyberpunk, Dynamic Angle, ... Neon City, Futuristic Clothing, Street Art, Hovering Cars” which is not there at all... How to describe the pictures correctly? Sorry for the lame questions, I'm not a very good Pythonist.

![Знімок екрана 2024-05-26 114221](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/63176aa8-3086-4039-99e5-1e15ec5f5fcd)

![Знімок екрана 2024-05-26 114802](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/4d9203d8-e848-42ec-9d81-f3093e843704)

![Знімок екрана 2024-05-26 114607](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/d6584d80-4356-4577-811f-eed9079f5ca9)



Ideally, I would like LLM to be able to separately describe what is in the picture, like “Teenage Boy, Riding Bicycle, on the street, blue t-shirt”, etc., and separately publish “by Hayao Miyadzaki, digital art, in ghibli style, manga”, etc...

**Comment by if-ai** [comment]
Yes this one I haven't seen it looks like you are doing everything correctly Maybe try the newer IF Chat node on SD mode, but you are doing everything correct there and it looks like an issue connecting with ollama maybe you update to the latest version, make sure ollama is running   and try the ip number 127.0.0.1 instead of localhost

**Comment by alexdoroga** [comment]
> Yes this one I haven't seen it looks like you are doing everything correctly Maybe try the newer IF Chat node on SD mode, but you are doing everything correct there and it looks like an issue connecting with ollama maybe you update to the latest version, make sure ollama is running and try the ip number 127.0.0.1 instead of localhost

I'm using the latest version of ollama - just installed it, and+ it's been updated recently. The “Ollama Generate” nodes work fine, but there's a lot of manual writing and very inconvenient nodes. 
Below is the result of what I got on your recommendation. ((

![Знімок екрана 2024-05-26 123140](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/4e25329b-1457-4230-a486-1cc4c46eb6b7)

[workflow (10).json](https://github.com/if-ai/ComfyUI-IF_AI_tools/files/15446922/workflow.10.json)

**Comment by if-ai** [comment]
yes on the screenshot you are not using llava anymore you need to use llava or other vision model to be able to see the image also clear empty the stop if you don't want keywords don't use the IFPromptIMG as it tries to add SD style keywords, please let me know if it works

**Comment by alexdoroga** [comment]
> don't use the IFPromptIMG as it tries to add SD style keywords
I'm sorry. I didn't understand how to do it here. On the screen below is a list of possible assistants. I found the SD option at the end and turned it on. 
![Знімок екрана 2024-05-26 130356](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/317a5eba-0f87-4523-a6b1-57d4aec2117b)

The second screenshot shows that the description did appear. I understand that i still need to use Ptompt to Prompt with the model “stable-diffusion-prompt-generator:latest” to turn it into usable prompt. I thought it was possible to get a nice prompt in one step, with one model)))
![Знімок екрана 2024-05-26 130958](https://github.com/if-ai/ComfyUI-IF_AI_tools/assets/148198168/36555853-c46a-4fb7-9b14-040b7f1e5e77)

And as for the style, I used the SDXL IP-adapter for the 10th time today and it worked out fine )))))) It turns out that you don't need to torture LLM ))) but it would be nice to get a description of the style, at least to find how the model describes it, understands it, etc.)

Thank you for your work - you have made a very cool repository ))

Greetings from Ukraine ))

**Comment by if-ai** [comment]
Thank you. I am glad I could help, also you can edit the profiles they are json files store on the custom_nodes/ComfyUI-IF_AI_tools folder you can make your own using IFpromptMKR_IMG as a base it can yield better results with a little editing close to what you expect, the same for the other presets you can edit then or make your own.
